showsite/show/urls.py
from django.conf.urls import url

from . import views


app_name = 'show'
urlpatterns = [
	url(r'index', views.index, name='index'),
	url(r'list', views.list_options, name='list'),
	url(r'show', views.show_conf, name='show'),
	url(r'compare_run', views.compare_run, name='compare_run'),
	url(r'logout', views.logout_view, name='logout_view'),
	url(r'(?P<file_name>.+)', views.file_show, name='file_show'),

]

showsite/showsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^show/', include('show.urls', namespace="show")),
    url(r'^admin/', admin.site.urls),
]

showsite/show/models.py
from django.db import models

# Create your models here.

# class User(models.Model):
# 	username = models.CharField(max_length=200)
# 	password = models.CharField(max_length=2000)
# 	privilege = models.CharField(max_length=100)
# 	def __str__(self):
# 		return self.username

class TextFiles(models.Model):
	os = models.CharField(max_length=200)
	func = models.CharField(max_length=200)
	lines = models.FilePathField(path="/etc/ansible/showsite/show/textfiles")

showsite/show/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.core.urlresolvers import reverse

from django.contrib.staticfiles.views import serve
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .models import TextFiles
import json
import showCommands
import datetime
import text2html
import re
import logging
import os
import diff
import mimetypes
# Create your views here.

username = ""
privilege = ""

hostname = ""
password = ""
host_user = ""
logged_in = False


def index(request):
	if request.method == 'GET':
		return render(request, 'show/index.html')
	else:
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is None:
			context = {'error_msg': "Invalid username or password"}
			return render(request, 'show/index.html', context)
		else:
			login(request, user)
			username = user.username
			response = HttpResponseRedirect(reverse('show:list'))
			return response
@login_required
def list_options(request):
	context = {'privilege': privilege}

	return render(request, 'show/list.html', context)

@login_required
def show_conf(request):
	if request.method == 'GET':
		return render(request, 'show/show.html')
	if request.method == 'POST':
		logger = logging.getLogger(__name__)
		logger.debug("HI")
		if request.POST.has_key('os'):
			os = request.POST['os']
			function = request.POST['function']
			textfile = get_object_or_404(TextFiles, os=os, func=function)
			with open(textfile.lines, 'r') as lines:
				textlines = [line for line in lines]
				return JsonResponse({'lines': textlines})

		else:
			hostname = request.POST['hostname']
			password = request.POST['password']
			host_user = request.POST['username']
			lines = request.POST['lines']
			commands = re.split("\n", lines)
			commands = commands[0:(len(commands) - 1)]
			outputfilename = ""
			items = re.split(' ', str(datetime.datetime.now()))
			for item in re.split(' ', str(datetime.datetime.now())):
				outputfilename = outputfilename + item + "_"
			outputfilename = outputfilename + host_user
			path = '/etc/ansible/showsite/show/show_outputs/'
			showCommands.execute(hostname, host_user, password, 
				commands, path + outputfilename +".txt")
			text2html.text2html(path + outputfilename+".txt", path + outputfilename+".html")
			file = open(path + outputfilename+'.html', 'r')
			response = HttpResponse(file.read(), content_type='text/html')
			response['Content-Disposition'] = 'attachment; filename="foo.html"'
			file.close()
			return response

@login_required
def compare_run(request):
	if request.method == 'GET':
		return render(request, 'show/compare_run.html')
	if request.method == 'POST':
		compare_hostname = ""
		if request.POST.has_key('hostname'):
			compare_hostname = request.POST['hostname']
			matched_items = []
			for item in os.listdir('/etc/ansible/showsite/show/show_outputs'):
				match = compare_hostname + ".txt"
				if re.search(match, item) != None:
					matched_items.append(item)
			return JsonResponse({'matched_items': matched_items})

		else:
			line_total = request.POST['lines']
			lines = re.split('\n', line_total)
			lines = lines[0: (len(lines) - 1)]
			path = '/etc/ansible/showsite/show/show_outputs/'
			path_comp = '/etc/ansible/showsite/show/compare_outputs/'
			outputfilename = ""
			items = re.split(' ', str(datetime.datetime.now()))
			for item in re.split(' ', str(datetime.datetime.now())):
				outputfilename = outputfilename + item + "_"
			outputfilename = "compare" + outputfilename + host_user
			diff.diff(path+lines[0], path+lines[1], path_comp+outputfilename)

			return JsonResponse({'data': outputfilename})

@login_required
def file_show(request, file_name):
	path_comp = '/etc/ansible/showsite/show/compare_outputs/'
	openfile = open(path_comp + file_name, 'r')
	response = HttpResponse(openfile.read())
	openfile.close()
	response['Content-Type'] = 'text/html'
	response['Content-Length'] =  str(os.stat(path_comp+file_name).st_size)
	response['Content-Encoding'] = 'UTF-8'
	response['Content-Disposition'] = 'attachment; ' + 'filename:"output.html"'
	return response

def logout_view(request):
	logout(request)
	return render(request, 'show/logout_success.html')

showsite/show/templates/show/compare_run.html
<!DOCTYPE html>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css"/>


<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<style>

	.navbar-default .navbar-fixed-top {
		background-color: #900C3F;
	}

	</style>
	<script>
	/* ============================================================
	 * bootstrap-dropdown.js v2.0.1
	 * http://twitter.github.com/bootstrap/javascript.html#dropdowns
	 * ============================================================
	 * Copyright 2012 Twitter, Inc.
	 *
	 * Licensed under the Apache License, Version 2.0 (the "License");
	 * you may not use this file except in compliance with the License.
	 * You may obtain a copy of the License at
	 *
	 * http://www.apache.org/licenses/LICENSE-2.0
	 *
	 * Unless required by applicable law or agreed to in writing, software
	 * distributed under the License is distributed on an "AS IS" BASIS,
	 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	 * See the License for the specific language governing permissions and
	 * limitations under the License.
	 * ============================================================ */


	!function( $ ){

	  "use strict"

	 /* DROPDOWN CLASS DEFINITION
	  * ========================= */

	  var toggle = '[data-toggle="dropdown"]'
	    , Dropdown = function ( element ) {
	        var $el = $(element).on('click.dropdown.data-api', this.toggle)
	        $('html').on('click.dropdown.data-api', function () {
	          $el.parent().removeClass('open')
	        })
	      }

	  Dropdown.prototype = {

	    constructor: Dropdown

	  , toggle: function ( e ) {
	      var $this = $(this)
	        , selector = $this.attr('data-target')
	        , $parent
	        , isActive

	      if (!selector) {
	        selector = $this.attr('href')
	        selector = selector && selector.replace(/.*(?=#[^\s]*$)/, '') //strip for ie7
	      }

	      $parent = $(selector)
	      $parent.length || ($parent = $this.parent())

	      isActive = $parent.hasClass('open')

	      clearMenus()
	      !isActive && $parent.toggleClass('open')

	      return false
	    }

	  }

	  function clearMenus() {
	    $(toggle).parent().removeClass('open')
	  }


	  /* DROPDOWN PLUGIN DEFINITION
	   * ========================== */

	  $.fn.dropdown = function ( option ) {
	    return this.each(function () {
	      var $this = $(this)
	        , data = $this.data('dropdown')
	      if (!data) $this.data('dropdown', (data = new Dropdown(this)))
	      if (typeof option == 'string') data[option].call($this)
	    })
	  }

	  $.fn.dropdown.Constructor = Dropdown


	  /* APPLY TO STANDARD DROPDOWN ELEMENTS
	   * =================================== */

	  $(function () {
	    $('html').on('click.dropdown.data-api', clearMenus)
	    $('body').on('click.dropdown.data-api', toggle, Dropdown.prototype.toggle)
	  })

	}( window.jQuery );
	</script>

    <title>Fixed Top Navbar Example for Bootstrap</title>


  </head>

  <body>
	<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Networking Webtools</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="list.html">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'show:show' %}">Running Configs</a></li>
                <li><a href="{%url 'show:compare_run' %}">Compare Previous Configs</a></li>
                <li><a href="#">Subnet Locator</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'show:logout_view' %}">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    </div>
    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Compare Previous Configs</h1>
        <div class="row">
        	<div class="col-md-4">
		        <div class="well" style="margin-top: 40px; margin-left: -20px; margin-right:-20px">
		        	<h4>Device Selection</h4>
		        	<form action = "{% url 'show:compare_run' %}" method="POST" id="form1">
		        	{% csrf_token %}
					  	
					  	<fieldset class="form-group">
					    	<label for="hostname">Enter Hostname</label>
					    	<input type="text" class="form-control" id="hostname">
					 	 </fieldset>
						<button type="submit" class="btn btn-default" id="form1submit">Submit</button>
					</form>


		        </div>
		    </div>
		    <div class="col-md-8">
		    	<div class="well" style="margin-top: 40px; margin-right:-20px">
		    		<h4>Previous Config List</h4>
		    		<form action="{% url 'show:compare_run'}" method="POST" id="form2" name="selectionForm">
		    		{% csrf_token %}
		    		<fieldset class="form-group">
				    	<label for="showList">Command List</label>
				    	<select multiple class="form-control" id="showList" name="selectValues">
				   		</select>
					</fieldset>
				  	<button id="form2submit" type="submit" a="_blank">Submit</button>
				  	<small class="text-muted" id="warning" style="visibility:hidden">Pick one choice.</small>
		    		</form>
		    	</div>
		    </div>
        </div>
        <div class="row">
        	<div class="col-md-12">
        		<iframe id="iframe" style="visibility:hidden"></iframe>
        	</div>
        </div>
	   	<script type='text/javascript'>
		function getCookie(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie != '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = jQuery.trim(cookies[i]);
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) == (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');
		$("#form1").on('submit', (function(e) {

		    var url_th = "{% url 'show:compare_run' %}"; // the script where you handle the form input.
		    var formData = {
		    	'hostname': $("#hostname").val(),
		    };
		    $.ajaxSetup({
			    crossDomain: false, // obviates need for sameOrigin test
			    beforeSend: function(xhr, settings) {
			        xhr.setRequestHeader("X-CSRFToken", csrftoken);
			    }
			});
		    $.ajax({
		    	url: url_th,
		    	type: "POST",
		    	data: formData,
		    	success: function(response){
		    		window.alert("Hi");
		    		var lines = response['matched_items'];
		    		var innerMarkup = "";
		    		for (var x = 0; x<lines.length; x++)
		    		{
		    			innerMarkup = innerMarkup + "<option>" + lines[x] + "</option>";
		    		}
		    		document.getElementById("showList").innerHTML = innerMarkup;
		    		console.log(response);
		    	}
		    });
		    e.preventDefault();

		}));
		console.log("hello");

		$("#showList").change(function(event){
			var lines = $("#showList").val() || [];
			if (lines.length > 2) {
				$("select option:selected").first().removeAttr("selected");
				$("#warning").css("visibility", "visible");
			}
			console.log("Changed");
		});

		$("#form2submit").click(function(e)
		{
			var url_th = "{% url 'show:compare_run' %}";
			var lines = $("#showList").val() || [];
			var line_total = "";
			for (var x = 0; x < lines.length; x++){
				line_total = line_total + lines[x] + "\n";
			}
			var formData = {
			    'lines': line_total,
			};

			$.ajaxSetup({
			    crossDomain: false, // obviates need for sameOrigin test
			    beforeSend: function(xhr, settings) {
			        xhr.setRequestHeader("X-CSRFToken", csrftoken);
			    }
			});

			$.ajax({
				url: url_th,
				type: "POST",
				data: formData,
				success: function(response){
					var data = response;
					var data_src = data['data'];
					//data_src = "show/" + data_src;
					console.log(data_src);
					location.replace(data_src);
					console.log(response);
				},
			});
		e.preventDefault();
			//var form = document.forms.selectionForm;
		 	// var values = "";
		 	// var x = 0;
		 	// for (x=0; x<form.selectValues.length; x++)
		 	// {
		 	// 	if (form.selectValues[x].selected)
		 	// 	{
		 	// 		values = form.selectValues[x].value + "\n";
		 	// 	}
		 	// }
		});
		</script>
      </div>

    </div> <!-- /container -->
  	<script src="assets/js/jquery.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>	
</body>


<!-- <script type='text/javascript'>
	function submitForm(){
		console.log("Logged");
		var formData = {
				'hostname' : $(#hostname).val(),
				'password' : $(#password).val(),
				'type' : $(#type).val(),

			};
			console.log(formData);

			$.ajax({
				type: 'POST',
				url: "{% url 'show:show'}",
				contentType: 'application/json; charset=utf-8',
				data: $.toJSON(formData),
				dataType: 'text',
			})
				.done(function(data) {
					console.log(data);


				});

			event.preventDefault();
	}
</script> -->


</html>

showsite/show/templates/show/index.html
<!DOCTYPE html>

<script type="text/javascript"
 src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js">
</script>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css"/>

<style>

.login_title{
	text-align: center;
}

.form_input_left{
	position:absolute;
	right: 30px;
	margin-top: 200px;
}

.form_input_right{
	position:absolute;
	left: 30px;
	margin-top: 200px;
}

.form_div{
	position:relative;
}

.form_inputs{
	border-color: #b3ecff
	border-radius: 4px;
	border-width: 3px;
}

.content{
	height:250px;
}

</style>

<html>
	<head>
		<title>Login Page</title>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row" style="background-color: #b30000">
					<h3 class="login_title">Networking Login Portal</h3>
			</div>
			<div class="row" style="height:10px; background-color:#000000">
			</div>
			{% if error_msg %}
				<div class="row" style="height:40px;">
					<p>{{ error_msg }}</p>
				</div>
			{% endif %}
			<div class="row content">
				<form action="{% url 'show:index' %}" method="post">
				{% csrf_token %}
					<div class="col-md-6 form_div">
						<div class="form_input_left">
							<input type="text" class="form-control form_inputs" name="username" placeholder="Username: " />
							<input type="text" style="display:none" value="True" name="bool" />
						</div>
					</div>
					<div class="col-md-6 form_div">
						<div class="form_input_right">
							<input type="text" class="form-control form_inputs" name="password" placeholder="Password: "/>
						</div>
					</div>
					<button type="submit" style="display:none" id="login_submit"></button>
				</form>
			</div>
			<div class="row">
				<div class="col-md-12" style="text-align:center">
					<button class="btn btn-default" onclick="clickFunction()" style="text-align:center">Login</button>
				</div>
			</div>
		</div>
	</body>

	<script type='text/javascript'>
		function clickFunction() {
			document.getElementById("login_submit").click();
		}	
	</script>
</html>

showsite/show/templates/show/list.html
<!DOCTYPE html>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css"/>

<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<style>

	.navbar-default .navbar-fixed-top {
		background-color: #900C3F;
	}

	</style>
	<script>
	/* ============================================================
	 * bootstrap-dropdown.js v2.0.1
	 * http://twitter.github.com/bootstrap/javascript.html#dropdowns
	 * ============================================================
	 * Copyright 2012 Twitter, Inc.
	 *
	 * Licensed under the Apache License, Version 2.0 (the "License");
	 * you may not use this file except in compliance with the License.
	 * You may obtain a copy of the License at
	 *
	 * http://www.apache.org/licenses/LICENSE-2.0
	 *
	 * Unless required by applicable law or agreed to in writing, software
	 * distributed under the License is distributed on an "AS IS" BASIS,
	 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	 * See the License for the specific language governing permissions and
	 * limitations under the License.
	 * ============================================================ */


	!function( $ ){

	  "use strict"

	 /* DROPDOWN CLASS DEFINITION
	  * ========================= */

	  var toggle = '[data-toggle="dropdown"]'
	    , Dropdown = function ( element ) {
	        var $el = $(element).on('click.dropdown.data-api', this.toggle)
	        $('html').on('click.dropdown.data-api', function () {
	          $el.parent().removeClass('open')
	        })
	      }

	  Dropdown.prototype = {

	    constructor: Dropdown

	  , toggle: function ( e ) {
	      var $this = $(this)
	        , selector = $this.attr('data-target')
	        , $parent
	        , isActive

	      if (!selector) {
	        selector = $this.attr('href')
	        selector = selector && selector.replace(/.*(?=#[^\s]*$)/, '') //strip for ie7
	      }

	      $parent = $(selector)
	      $parent.length || ($parent = $this.parent())

	      isActive = $parent.hasClass('open')

	      clearMenus()
	      !isActive && $parent.toggleClass('open')

	      return false
	    }

	  }

	  function clearMenus() {
	    $(toggle).parent().removeClass('open')
	  }


	  /* DROPDOWN PLUGIN DEFINITION
	   * ========================== */

	  $.fn.dropdown = function ( option ) {
	    return this.each(function () {
	      var $this = $(this)
	        , data = $this.data('dropdown')
	      if (!data) $this.data('dropdown', (data = new Dropdown(this)))
	      if (typeof option == 'string') data[option].call($this)
	    })
	  }

	  $.fn.dropdown.Constructor = Dropdown


	  /* APPLY TO STANDARD DROPDOWN ELEMENTS
	   * =================================== */

	  $(function () {
	    $('html').on('click.dropdown.data-api', clearMenus)
	    $('body').on('click.dropdown.data-api', toggle, Dropdown.prototype.toggle)
	  })

	}( window.jQuery );


	</script>

    <title>Fixed Top Navbar Example for Bootstrap</title>


  </head>

  <body>
	<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Networking Webtools</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="list.html">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'show:show' %}">Running Configs</a></li>
                <li><a href="{% url 'show:compare_run' %}">Compare Previous Configs</a></li>
                <li><a href="#">Subnet Locator</a></li>
                {% if privilege == 'admin' %}
                <li><a href="#">Something else here</a></li>
                {% else %}
                {% endif %}
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'show:logout_view' %}">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    </div>
    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>To see the difference between static and fixed top navbars, just scroll.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs »</a>
        </p>
       </div>
    </div> <!-- /container -->
  	<script src="assets/js/jquery.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>	

</body>
</html>

showsite/show/templates/show/logout_success.html
<!DOCTYPE html>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css"/>

<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<style>

	.navbar-default .navbar-fixed-top {
		background-color: #900C3F;
	}

	</style>

    <title>Fixed Top Navbar Example for Bootstrap</title>


  </head>

  <body>
	<!-- Fixed navbar -->

    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h4>Return to Login</h4>
          <a class="btn btn-lg btn-primary" href="{% url 'show:index' %}" role="button">Login Page »</a>
        </p>
       </div>
    </div> <!-- /container -->
  	<script src="assets/js/jquery.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>	

</body>
</html>